# Generated by Django 4.0.5 on 2022-06-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='picture',
            field=models.ImageField(upload_to='medications/photos'),
        ),
        migrations.CreateModel(
            name='DispacherDrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField(blank=True, default=0, editable=False)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
                ('medications', models.ManyToManyField(to='drone.medication')),
            ],
        ),
    ]
